parameters:
    question_bank.question.max_options: '%env(int:default::QUESTION_BANK_MAX_OPTIONS)%'
    question_bank.question.max_content_length: '%env(int:default::QUESTION_BANK_MAX_CONTENT_LENGTH)%'
    question_bank.category.max_depth: '%env(int:default::QUESTION_BANK_CATEGORY_MAX_DEPTH)%'
    question_bank.category.cache_ttl: '%env(int:default::QUESTION_BANK_CATEGORY_CACHE_TTL)%'
    question_bank.tag.max_per_question: '%env(int:default::QUESTION_BANK_TAG_MAX_PER_QUESTION)%'
    question_bank.tag.auto_slug: '%env(bool:default::QUESTION_BANK_TAG_AUTO_SLUG)%'
    question_bank.search.engine: '%env(default::QUESTION_BANK_SEARCH_ENGINE)%'
    question_bank.search.min_query_length: '%env(int:default::QUESTION_BANK_SEARCH_MIN_QUERY_LENGTH)%'

    env(QUESTION_BANK_MAX_OPTIONS): '10'
    env(QUESTION_BANK_MAX_CONTENT_LENGTH): '5000'
    env(QUESTION_BANK_CATEGORY_MAX_DEPTH): '5'
    env(QUESTION_BANK_CATEGORY_CACHE_TTL): '3600'
    env(QUESTION_BANK_TAG_MAX_PER_QUESTION): '10'
    env(QUESTION_BANK_TAG_AUTO_SLUG): 'true'
    env(QUESTION_BANK_SEARCH_ENGINE): 'database'
    env(QUESTION_BANK_SEARCH_MIN_QUERY_LENGTH): '2'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # 具体子目录注册，避免通配符
    Tourze\QuestionBankBundle\Repository\:
        resource: '../../Repository'

    Tourze\QuestionBankBundle\Service\:
        resource: '../../Service'

    Tourze\QuestionBankBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
